spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # DataBase info
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    # password:
  # JPA
  jpa:
    database-platform: H2
    # show-sql: true # sql문 확인 시 주석 해제
    # generate-ddl: true
    hibernate:
      ddl-auto: create # 운영, 스테이징 단계 : validate
    open-in-view: false
  sql:
    init:
      mode: always