spring:
  jpa:
    defer-datasource-initialization: true
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  # DataBase info
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    # password:

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true