spring:
  servlet:
    multipart:
      max-file-size: 20MB
      location:
  jpa:
    defer-datasource-initialization: true
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  # DataBase info
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


ncp:
  storage:
    end-point: https://kr.object.ncloudstorage.com
    region: kr-standard
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    bucket: ${NCP_BUCKET_NAME}