spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # DataBase info
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    # password: